import { js } from "cc";
import { GuideLay } from "./manager/Guide";
import { BagPanel } from "./module/bag/BagPanel";
import { ComposePanel } from "./module/bag/ComposePanel";
import { OpenBoxPanel } from "./module/bag/OpenBoxPanel";
import { CardCollectPanel } from "./module/cardCollect/CardCollectPanel";
import { CardGroupCreatorTips } from "./module/cards/CardGroupCreatorTips";
import { cardGroupSettingTips } from "./module/cards/cardGroupSettingTips";
import { CardInfoPanel } from "./module/cards/CardInfoPanel";
import { CardsPanel } from "./module/cards/CardsPanel";
import { CardTipsPanel } from "./module/common/CardTipsPanel";
import { ClickTipsPanel } from "./module/common/ClickTipsPanel";
import { ItemTips } from "./module/common/ItemTips";
import { MsgPanel } from "./module/common/MsgPanel";
import { RewardTips } from "./module/common/RewardTips";
import { Tips } from "./module/common/Tips";
import { Tips2 } from "./module/common/Tips2";
import { Tips3 } from "./module/common/Tips3";
import { FightLogPanel } from "./module/fight/FightLogPanel";
import { FightUI } from "./module/fight/FightUI";
import { SeasonSettlePanel } from "./module/fight/SeasonSettlePanel";
import { FriendBindOrUnbindPanel } from "./module/friend/FriendBindOrUnbindPanel";
import { FriendIncomeListPanel } from "./module/friend/FriendIncomeListPanel";
import { FriendInfoPanel } from "./module/friend/FriendInfoPanel";
import { FriendInviteListPanel } from "./module/friend/FriendInviteListPanel";
import { FriendListPanel } from "./module/friend/FriendListPanel";
import { FriendPanel } from "./module/friend/FriendPanel";
import { HomePanel } from "./module/home/HomePanel";
import { LoginPanel } from "./module/login/LoginPanel";
import { ServerPanel } from "./module/login/ServerPanel";
import { MailDeletePanel } from "./module/mail/MailDeletePanel";
import { MailPanel } from "./module/mail/MailPanel";
import { MainPanel } from "./module/main/MainPanel";
import { TopUI } from "./module/main/TopUI";
import { GatePassBuyPanel } from "./module/rights/GatePassBuyPanel";
import { RightsPanel } from "./module/rights/RightsPanel";
import { RoomPanel } from "./module/room/RoomPanel";
import { ShopBuyPanel } from "./module/shop/ShopBuyPanel";
import { ShopLuckyBuyPanel } from "./module/shop/ShopLuckyBuyPanel";
import { ShopPanel } from "./module/shop/ShopPanel";
import { ShopRefreshPanel } from "./module/shop/ShopRefreshPanel";
import { TaskPanel } from "./module/task/TaskPanel";
import { BuyPanel } from "./module/trade/BuyPanel";
import { SortPanel } from "./module/trade/SortPanel";
import { TradeCreateOrderPanel } from "./module/trade/TradeCreateOrderPanel";
import { TradePanel } from "./module/trade/TradePanel";
import { UserEditInfoPanel } from "./module/userInfo/UserEditInfoPanel";
import { UserHeadPanel } from "./module/userInfo/UserHeadPanel";
import { UserInfoPanel } from "./module/userInfo/UserInfoPanel";
import { VSCardGroupPanel } from "./module/vs/VSCardGroupPanel";
import { VSModelPanel } from "./module/vs/VSModelPanel";
import { VSPanel } from "./module/vs/VSPanel";
import { VSSeasonFightLogPanel } from "./module/vs/VSSeasonFightLogPanel";
import { VSSeasonTipsPanel } from "./module/vs/VSSeasonTipsPanel";
import { VSSectionAwardPanel } from "./module/vs/VSSectionAwardPanel";
import { VSStarElementFightLogPanel } from "./module/vs/VSStarElementFightLogPanel";
import { Out_AddCard } from "./module/fight/opOutput/Out_AddCard";
import { Out_AddCardToDeck } from "./module/fight/opOutput/Out_AddCardToDeck";
import { Out_AddCardToHand } from "./module/fight/opOutput/Out_AddCardToHand";
import { Out_AddCardToTerrain } from "./module/fight/opOutput/Out_AddCardToTerrain";
import { Out_BattleRoomOpOutput_TerrainData } from "./module/fight/opOutput/Out_BattleRoomOpOutput_TerrainData";
import { Out_CardDataChange } from "./module/fight/opOutput/Out_CardDataChange";
import { Out_CardDeckFrontToHandTail } from "./module/fight/opOutput/Out_CardDeckFrontToHandTail";
import { Out_CardTerrainState } from "./module/fight/opOutput/Out_CardTerrainState";
import { Out_CopyCard } from "./module/fight/opOutput/Out_CopyCard";
import { Out_DeckToDel } from "./module/fight/opOutput/Out_DeckToDel";
import { Out_DeckToDrop } from "./module/fight/opOutput/Out_DeckToDrop";
import { Out_DelToHand } from "./module/fight/opOutput/Out_DelToHand";
import { Out_DropToHand } from "./module/fight/opOutput/Out_DropToHand";
import { Out_EffectSkill } from "./module/fight/opOutput/Out_EffectSkill";
import { Out_HandToDeck } from "./module/fight/opOutput/Out_HandToDeck";
import { Out_HandToDel } from "./module/fight/opOutput/Out_HandToDel";
import { Out_HandToDrop } from "./module/fight/opOutput/Out_HandToDrop";
import { Out_HandToTerrain } from "./module/fight/opOutput/Out_HandToTerrain";
import { Out_LockZone } from "./module/fight/opOutput/Out_LockZone";
import { Out_NewRound } from "./module/fight/opOutput/Out_NewRound";
import { Out_Nullify } from "./module/fight/opOutput/Out_Nullify";
import { Out_Peek } from "./module/fight/opOutput/Out_Peek";
import { Out_PlayerEnergy } from "./module/fight/opOutput/Out_PlayerEnergy";
import { Out_PlayerPower } from "./module/fight/opOutput/Out_PlayerPower";
import { Out_Protect } from "./module/fight/opOutput/Out_Protect";
import { Out_RetransmissionRound } from "./module/fight/opOutput/Out_RetransmissionRound";
import { Out_RoomDestroy } from "./module/fight/opOutput/Out_RoomDestroy";
import { Out_RoundData } from "./module/fight/opOutput/Out_RoundData";
import { Out_Settlement } from "./module/fight/opOutput/Out_Settlement";
import { Out_TerrainToDel } from "./module/fight/opOutput/Out_TerrainToDel";
import { Out_TerrainToDrop } from "./module/fight/opOutput/Out_TerrainToDrop";
import { Out_TerrainToTerrain } from "./module/fight/opOutput/Out_TerrainToTerrain";
import { Out_WaitPlayerInput } from "./module/fight/opOutput/Out_WaitPlayerInput";
import { Out_WaitPlayerShow } from "./module/fight/opOutput/Out_WaitPlayerShow";

export class RegisterClass {
    constructor() {
      js.setClassName("GuideLay", GuideLay);
      js.setClassName("BagPanel", BagPanel);
      js.setClassName("ComposePanel", ComposePanel);
      js.setClassName("OpenBoxPanel", OpenBoxPanel);
      js.setClassName("CardCollectPanel", CardCollectPanel);
      js.setClassName("CardGroupCreatorTips", CardGroupCreatorTips);
      js.setClassName("cardGroupSettingTips", cardGroupSettingTips);
      js.setClassName("CardInfoPanel", CardInfoPanel);
      js.setClassName("CardsPanel", CardsPanel);
      js.setClassName("CardTipsPanel", CardTipsPanel);
      js.setClassName("ClickTipsPanel", ClickTipsPanel);
      js.setClassName("ItemTips", ItemTips);
      js.setClassName("MsgPanel", MsgPanel);
      js.setClassName("RewardTips", RewardTips);
      js.setClassName("Tips", Tips);
      js.setClassName("Tips2", Tips2);
      js.setClassName("Tips3", Tips3);
      js.setClassName("FightLogPanel", FightLogPanel);
      js.setClassName("FightUI", FightUI);
      js.setClassName("SeasonSettlePanel", SeasonSettlePanel);
      js.setClassName("FriendBindOrUnbindPanel", FriendBindOrUnbindPanel);
      js.setClassName("FriendIncomeListPanel", FriendIncomeListPanel);
      js.setClassName("FriendInfoPanel", FriendInfoPanel);
      js.setClassName("FriendInviteListPanel", FriendInviteListPanel);
      js.setClassName("FriendListPanel", FriendListPanel);
      js.setClassName("FriendPanel", FriendPanel);
      js.setClassName("HomePanel", HomePanel);
      js.setClassName("LoginPanel", LoginPanel);
      js.setClassName("ServerPanel", ServerPanel);
      js.setClassName("MailDeletePanel", MailDeletePanel);
      js.setClassName("MailPanel", MailPanel);
      js.setClassName("MainPanel", MainPanel);
      js.setClassName("TopUI", TopUI);
      js.setClassName("GatePassBuyPanel", GatePassBuyPanel);
      js.setClassName("RightsPanel", RightsPanel);
      js.setClassName("RoomPanel", RoomPanel);
      js.setClassName("ShopBuyPanel", ShopBuyPanel);
      js.setClassName("ShopLuckyBuyPanel", ShopLuckyBuyPanel);
      js.setClassName("ShopPanel", ShopPanel);
      js.setClassName("ShopRefreshPanel", ShopRefreshPanel);
      js.setClassName("TaskPanel", TaskPanel);
      js.setClassName("BuyPanel", BuyPanel);
      js.setClassName("SortPanel", SortPanel);
      js.setClassName("TradeCreateOrderPanel", TradeCreateOrderPanel);
      js.setClassName("TradePanel", TradePanel);
      js.setClassName("UserEditInfoPanel", UserEditInfoPanel);
      js.setClassName("UserHeadPanel", UserHeadPanel);
      js.setClassName("UserInfoPanel", UserInfoPanel);
      js.setClassName("VSCardGroupPanel", VSCardGroupPanel);
      js.setClassName("VSModelPanel", VSModelPanel);
      js.setClassName("VSPanel", VSPanel);
      js.setClassName("VSSeasonFightLogPanel", VSSeasonFightLogPanel);
      js.setClassName("VSSeasonTipsPanel", VSSeasonTipsPanel);
      js.setClassName("VSSectionAwardPanel", VSSectionAwardPanel);
      js.setClassName("VSStarElementFightLogPanel", VSStarElementFightLogPanel);
      js.setClassName("Out_AddCard", Out_AddCard);
      js.setClassName("Out_AddCardToDeck", Out_AddCardToDeck);
      js.setClassName("Out_AddCardToHand", Out_AddCardToHand);
      js.setClassName("Out_AddCardToTerrain", Out_AddCardToTerrain);
      js.setClassName("Out_BattleRoomOpOutput_TerrainData", Out_BattleRoomOpOutput_TerrainData);
      js.setClassName("Out_CardDataChange", Out_CardDataChange);
      js.setClassName("Out_CardDeckFrontToHandTail", Out_CardDeckFrontToHandTail);
      js.setClassName("Out_CardTerrainState", Out_CardTerrainState);
      js.setClassName("Out_CopyCard", Out_CopyCard);
      js.setClassName("Out_DeckToDel", Out_DeckToDel);
      js.setClassName("Out_DeckToDrop", Out_DeckToDrop);
      js.setClassName("Out_DelToHand", Out_DelToHand);
      js.setClassName("Out_DropToHand", Out_DropToHand);
      js.setClassName("Out_EffectSkill", Out_EffectSkill);
      js.setClassName("Out_HandToDeck", Out_HandToDeck);
      js.setClassName("Out_HandToDel", Out_HandToDel);
      js.setClassName("Out_HandToDrop", Out_HandToDrop);
      js.setClassName("Out_HandToTerrain", Out_HandToTerrain);
      js.setClassName("Out_LockZone", Out_LockZone);
      js.setClassName("Out_NewRound", Out_NewRound);
      js.setClassName("Out_Nullify", Out_Nullify);
      js.setClassName("Out_Peek", Out_Peek);
      js.setClassName("Out_PlayerEnergy", Out_PlayerEnergy);
      js.setClassName("Out_PlayerPower", Out_PlayerPower);
      js.setClassName("Out_Protect", Out_Protect);
      js.setClassName("Out_RetransmissionRound", Out_RetransmissionRound);
      js.setClassName("Out_RoomDestroy", Out_RoomDestroy);
      js.setClassName("Out_RoundData", Out_RoundData);
      js.setClassName("Out_Settlement", Out_Settlement);
      js.setClassName("Out_TerrainToDel", Out_TerrainToDel);
      js.setClassName("Out_TerrainToDrop", Out_TerrainToDrop);
      js.setClassName("Out_TerrainToTerrain", Out_TerrainToTerrain);
      js.setClassName("Out_WaitPlayerInput", Out_WaitPlayerInput);
      js.setClassName("Out_WaitPlayerShow", Out_WaitPlayerShow);
   }
}